export const primaryInfo = [
  {
    type: "text",
    label: "Employee ID",
    name: "empId",
  },
  {
    type: "text",
    label: "Employee Name",
    name: "empName",
  },
  {
    type: "Date",
    label: "Date of Joining",
    name: "doj",
  },
  {
    type: "Date",
    label: "Date of Birth",
    name: "dob",
  },
  {
    type: "email",
    label: "E-mail ID",
    name: "email",
  },
  {
    type: "text",
    label: "Blood Group",
    name: "bloodGroup",
  },
  {
    type: "Select",
    label: "Designation",
    name: "designation",
  },
  {
    type: "Select",
    label: "Gender",
    name: "gender",
  },
  {
    type: "Select",
    label: "Nationality",
    name: "nationality",
  },
  {
    type: "Select",
    label: "Employee Status",
    name: "empStatus",
  },
];
export const empstatus = ["Permenent", "Contract", "Trainee", "On Probation"];
export const nationality = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export const designation = [
  "Sr.Software Enginner",
  "Jr.software Engg",
  "HR",
  "Admin",
];
export const gender = ["Male", "Female", "Other"];

export const secondaryInfo = [
  {
    type: "text",
    label: "Pan No",
    name: "panNo",
  },
  {
    type: "number",
    label: "Aadhar No",
    name: "aadharNo",
  },
  {
    type: "text",
    label: "Father Name",
    name: "fatherName",
  },
  {
    type: "text",
    label: "Mother Name ",
    name: "motherName",
  },
  {
    type: "text",
    label: "Spouse Name",
    name: "spouseName",
  },
  {
    type: "text",
    label: "Passport No",
    name: "passportNo",
  },
  {
    type: "Select",
    label: "Martal Status",
    name: "maritalStatus",
  },
];

export const maritalStatus = ["Married", "Unmarried", "Divorsed"];

export const educationDetails = [
  {
    type: "Select",
    label: "Education Type",
    name: "educationType",
  },
  {
    type: "text",
    label: "Year of Passing",
    name: "yop",
  },
  {
    type: "text",
    label: "Percentage(%)",
    name: "percentage",
  },
  {
    type: "Select",
    label: "University Name",
    name: "universityName",
  },
  {
    type: "text",
    label: "Institute Name",
    name: "instituteName",
  },
  {
    type: "text",
    label: "Specialization",
    name: "specialization",
  },
  {
    type: "Select",
    label: "State",
    name: "state",
  },
];
export const universityName = ["SSPU", "MU", "SU", "BATU", "BV"];
export const educationType = ["PG", "UG", "Phd"];

export const addressDetails = [
  {
    type: "Select",
    label: "Address Type",
    name: "addressType",
  },
  {
    type: "text",
    label: "Door No",
    name: "doorNo",
  },
  {
    type: "text",
    label: "Street",
    name: "street",
  },
  {
    type: "text",
    label: "Locality",
    name: "locality",
  },
  {
    type: "text",
    label: "City",
    name: "city",
  },
  {
    type: "Select",
    label: "State",
    name: "state",
  },
  {
    type: "number",
    label: "Pin Code",
    name: "pinCode",
  },
  {
    type: "text",
    label: "Landmark",
    name: "landmark",
  },
];
export const addressType = [
  "Permenent",
  "Temperary",
  "Office",
  "Billing",
  "Shipping",
];
export const state = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];

export const bankDetails = [
  {
    type: "text",
    label: "Account No.",
    name: "accountNo",
  },
  {
    type: "text",
    label: "Bank Name",
    name: "bankName",
  },
  {
    type: "Select",
    label: "Account Type",
    name: "accountType",
  },
  {
    type: "text",
    label: "IFSC Code",
    name: "ifscCode",
  },
  {
    type: "Select",
    label: "Branch",
    name: "branch",
  },
  {
    type: "Select",
    label: "State",
    name: "state",
  },
];
export const accountType = ["Saving", "Current", "PPF"];
export const Contact = [
  {
    type: "Select",
    label: "Contact Type",
    name: "contactType",
  },
  {
    type: "tel",
    label: "Contact Number",
    name: "contactNumber",
  },
];
export const contactType = ["Moblie", "Landline"];
export const technicalSkill = [
  {
    type: "text",
    label: "Skill Type",
    name: "skillType",
  },
  {
    type: "text",
    label: "Skill Rating",
    name: "skillRating",
  },
  {
    type: "Select",
    label: "Years of Experience (over skill)",
    name: "yoExperience",
  },
];

export const experience = [1, 2, 3, 4, 5];
export const experiencData = [
  {
    type: "text",
    label: "Company Name",
    name: "companyName",
  },
  {
    type: "text",
    label: "Years of Experience",
    name: "yearsOfExperience",
  },
  {
    type: "Date",
    label: "Date of Joining",
    name: "dateOfJoining",
  },
  {
    type: "Date",
    label: "Date of Releaving",
    name: "dateOfReleaving",
  },
  {
    type: "Select",
    label: "Designation",
    name: "desiganation",
  },
  {
    type: "text",
    label: "Location",
    name: "location",
  },
];
